package com.nexus;

public class ExceptionDemo {

	public static void main(String[] args) {
	System.out.println("First Line");
	System.out.println("Second Line");
	
	int a = 10/0;    /* Due to write the wrong code line on the line no 9 the exception are occured due to
	 that reason the reamaining code is not executed the reamaining code is teminated due to the exception */
	
	System.out.println("Third Line");
	
	System.out.println("Fourth Line");
	System.out.println("Fifth Line");
	
	System.out.println("Sixth Line");
	
	}

}
